### ISSUE TITLE
sendMessageBatch failure

### ISSUE THREAD

**Issue by skiz** [XervoIO/aws-sqs#1]
When attempting to send a batch of messages I receive the following error:

The action SendMessageBatch is not valid for this endpoint.

The endpoint is simliar to "/123123123/nameofqueue"

The batch looks like

[
 {message: 'foo'},
 {message: 'bar'}
]

> sqs.sendMessageBatch(sqs_target_queue, [{message:'winning'}], function(e,r){ console.log(e); })
> undefined
> The action SendMessageBatch is not valid for this endpoint.

**Comment by zwigby** [comment]
Fix was just pushed to master.
