### ISSUE TITLE
Signature Error

### ISSUE THREAD

**Issue by tomasz-jomedia** [XervoIO/aws-sqs#12]
Hi, 

I'm testing your package, and I'm getting:
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

I've used the same config with the npm "sqs" extension and it works fine but I prefer yours. 

Using "us-east-1" for region. 

My Code:

```
var SQS = require('aws-sqs');

var sqs = new SQS(
        "access", 
        "secret",
        {region: "us-east-1"}
);

sqs.getQueueUrl("name", function(err, queue) {
    if(err) {
        console.log(err);
    } else {
        sqs.sendMessage(queue, "test", function(err, res) {
            if(err) {
                console.log(err);
            } else {
                console.log(res);
            }
        });     
    }
});
```

**Comment by tzmanics** [comment]
Hi @tomasz-jomedia sorry for the big delay, let us know if you are still working on this issue or have any other questions. For now I'm going to close this issue but please feel free to re-open. Thanks!
