### ISSUE TITLE
error:  The action DeleteMessageBatch is not valid for this endpoint.

### ISSUE THREAD

**Issue by mavrick** [XervoIO/aws-sqs#3]
Please add version opts otherwise will error.

SQS.prototype.deleteMessageBatch = function(queue, messageReceipts, fn) {
  var aws = awsjs.createSQSClient(
    this.accessKeyId,
    this.secretAccessKey,
    {
      host : this.host,
      path : queue,
      version: '2011-10-01', // added to fix error on deleteMessageBatch
      secure: true
  });

  var params = {};

  for(var i = 1; i <= messageReceipts.length; i++) {
    params['DeleteMessageBatchRequestEntry.'  + i + '.Id'] = 'message_' + i;
    params['DeleteMessageBatchRequestEntry.'  + i + '.ReceiptHandle'] = messageReceipts[i-1];
  }

  makeCall(aws, 'DeleteMessageBatch', params, function(err, result) {
    fn(err);
  });
};

**Comment by patricklodder** [comment]
This was fixed in e4423ac1 by @nhassan
