### ISSUE TITLE
Not working when region changed

### ISSUE THREAD

**Issue by mahasooq** [XervoIO/aws-sqs#4]
HI,
When I have changed the queue region to us-west-1  , i get a error like

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

But , it works well for the region 'us-east-1'. 
When I have checked the source , the host you have give is of the form
 'sqs.' + this.region + '.amazonaws.com';

But in the queue url for the one I have created in  'us-west-1'  looks like 
https://us-west-1.queue.amazonaws.com/XXXXXXXX/YYYYYYY

Thanks 
Mahasooq

**Comment by zwigby** [comment]
This pull has been published to npm.
