### ISSUE TITLE
Add getQueueAttributes action

### ISSUE THREAD

**Issue by pierre-b** [XervoIO/aws-sqs#7]
Hi guys,
Could you please add the getQueueAttributes action ? It's quite usefull to get stats on the queues.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/Query_QueryGetQueueAttributes.html

Best regards

**Comment by zwigby** [comment]
getQueueAttributes have been added thanks to patrick

**Comment by pierre-b** [comment]
Thanks guys !
